version: "3.8"
services:
  bot:
    build:
      context: .
    container_name: 'AiogramShopBot'
    environment:
      WEBHOOK_PATH: ""
      WEBAPP_HOST: "0.0.0.0" # Don't touch this
      WEBAPP_PORT: 5000 # Here your port
      TOKEN: "7113546929:AAEBaIJvMn5ZISnyJPi8Vk2bPEKHkQYP0AE" # Here your bot token from botfather
      NGROK_TOKEN: '2fbL9nE7y7Vhwv6tQa3gpSWOUlO_69GnQ3nbnxh4WjBuQYubC' # Here your ngrok token from ngrok.com
      ADMIN_ID_LIST: "1096758909" # Telegram ID's for admins;
      SUPPORT_LINK: "https://t.me/xEnotWhyNotx"
      DB_NAME: "database.db" # Here your database name
      PAGE_ENTRIES: 20 # Items per page
    ports:
      - "4040:4040"
      - "5000:5000" # ${WEBAPP_PORT}:${WEBAPP_PORT}
    expose:
      - 4040
      - 5000 # ${WEBAPP_PORT}
    volumes:
      - /AiogramShopBot:/bot/data
    command: ["python", "-u", "run.py"]

volumes:
  AiogramShopBot: